-- ============================================================================
-- Distributed Query Executor — WarehousePG(Greenplum 7 계열) 통합 스키마
-- ============================================================================
-- WarehousePG 는 Greenplum 7 계보(PostgreSQL 12 엔진)이므로 이 앱이 쓰는
-- PostgreSQL 기능(JSONB / INSERT … ON CONFLICT / CREATE INDEX IF NOT EXISTS /
-- ALTER TABLE … ADD COLUMN IF NOT EXISTS / DISTINCT ON)을 모두 그대로 지원한다.
-- 따라서 파이썬 코드(UPSERT·JSONB 직렬화)는 수정할 필요가 없고, 이 스키마 파일만
-- MPP 규칙에 맞게 조정하면 된다. 일반 PostgreSQL 판은 postgresql.sql 을 쓴다.
--
-- 적용:  psql "postgresql://user:pass@wpg-host:5432/queryexec" -f warehousepg.sql
--
-- 스키마: 모든 메타 테이블은 public 스키마로 명시 한정한다. 앱 설정 db.schema(기본 public)와
--   반드시 일치해야 한다(앱 런타임 SQL 도 db.schema 로 한정). 다른 스키마면 db.schema 와
--   이 파일의 public. 를 함께 치환할 것.
--
-- 시각 컬럼은 모두 KST(Asia/Seoul) 기준의 타임존 없는 TIMESTAMP 다(한국 단일 리전 — UTC/
-- 타임존 불필요). 기본값은 now() AT TIME ZONE 'Asia/Seoul'. 앱이 직접 넣는 시각도 KST naive.
--
-- ── postgresql.sql 대비 차이(왜) ───────────────────────────────────────────
--  1) 모든 테이블에 DISTRIBUTED BY 추가. MPP 는 분산키가 필요하고, 미지정 시
--     첫 컬럼/랜덤으로 잡혀 NOTICE 가 뜨고 데이터 편향이 생길 수 있다.
--  2) PRIMARY KEY/UNIQUE 가 있으면 분산키는 그 컬럼들의 부분집합이어야 한다.
--     기존 PK(job_id / executor_id / coordinator_id / (executor_url,coordinator_id))는
--     그대로 분산키로 적합하므로 PK 는 유지하고 DISTRIBUTED BY 만 맞춘다.
--  3) history/metrics 3개 테이블의 대리키 BIGSERIAL PRIMARY KEY 는 제거한다.
--     - 앱은 이 id 를 전혀 읽지 않는다(조회는 DISTINCT ON (job_id/task_id) … 기반).
--     - PK 를 두면 분산키가 (id)로 강제되어 job 단위 조회·dedup 이 전 세그먼트로
--       흩어진다. 대신 DISTRIBUTED BY (job_id)(또는 executor_url)로 co-locate 하면
--       DISTINCT ON 이 세그먼트 로컬에서 motion 없이 처리된다. id 는 디버그/정렬용
--       IDENTITY 컬럼으로만 남긴다.
--  4) 모든 테이블은 UPDATE/UPSERT 가 있거나 append 위주라 heap(기본)으로 둔다.
--     append-optimized/컬럼형으로 만들면 단건 UPDATE·UPSERT 에 부적합하다.
--
-- 주의: executor_status/coordinator_status/executor_reservation 은 수 초 간격의
-- 단일행 UPSERT/heartbeat 라 MPP 의 강점과는 반대 워크로드다. 볼륨이 작아 동작은
-- 하지만, 성능이 중요하면 이 메타 저장소(history.db_dsn)는 PostgreSQL 로 두고
-- Greenplum/WarehousePG 는 데이터 적재 대상(greenplum.dsn)으로만 쓰는 편이 낫다.
--
-- 테이블별 사용 DSN/설정:
--   jobs                    : store.backend=postgres (멀티 coordinator 공유 Job 저장소)
--   job_history             : history.db_dsn         (coordinator, job 단위 실행 이력)
--   task_history            : history.db_dsn         (executor, task 단위 실행 이력)
--   executor_status         : history.db_dsn         (executor.self_report=true 상태)
--   executor_health_metrics : monitor.db_dsn         (coordinator 헬스/메트릭 기록)
-- 보통 history.db_dsn 하나에 jobs/job_history/task_history/executor_status 를 함께 둔다.
-- ============================================================================


-- ─────────────────────────────────────────────────────────────────────────
-- 1) jobs — 멀티 coordinator 공유 Job 저장소 (store.backend=postgres)
--    PK(job_id)와 분산키(job_id)가 일치 → 재분배 없이 job_id 로 조회/UPSERT.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.jobs (
    job_id           TEXT PRIMARY KEY,
    coordinator_id   TEXT,
    status           TEXT,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at       TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Seoul'),
    data             JSONB NOT NULL
)
DISTRIBUTED BY (job_id);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON public.jobs (status);
CREATE INDEX IF NOT EXISTS idx_jobs_updated_at ON public.jobs (updated_at);
-- 요청 멱등(Idempotency-Key): 조회 가속용 표현식 인덱스. WarehousePG(GP)는 UNIQUE 인덱스가
-- 분산키(job_id)를 포함해야 하는데 idempotency_key 는 분산키가 아니라 UNIQUE 를 걸 수 없다.
-- 그래서 여기서는 비-UNIQUE 로 두고, 멱등 보장은 앱 레벨 조회(get_by_idempotency_key)로만 한다
-- (단일 coordinator 는 완전, 멀티 coordinator 는 best-effort — 강한 보장이 필요하면 메타DB를 PostgreSQL 로).
CREATE INDEX IF NOT EXISTS idx_jobs_idempotency_key
    ON public.jobs ((data->>'idempotency_key'));


-- ─────────────────────────────────────────────────────────────────────────
-- 2) job_history — coordinator 의 job 단위 실행 이력 (history.db_dsn)
--    run() 안에서 상태 전이(시작=RUNNING, 종료=DONE/PARTIAL/FAILED)마다 append.
--    DISTRIBUTED BY (job_id): 대시보드의 DISTINCT ON (job_id) dedup 을 세그먼트
--    로컬에서 처리. id 는 PK 가 아니라 정렬/디버그용 IDENTITY 컬럼으로만 둔다.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_history (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recorded_at        TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Seoul'),
    job_id             TEXT NOT NULL,
    username           TEXT,
    status             TEXT NOT NULL,
    partition_column   TEXT,
    target_table       TEXT,
    parallelism        INTEGER,
    total_tasks        INTEGER,
    completed_tasks    INTEGER,
    total_rows_written BIGINT,
    error              TEXT,
    created_at         TIMESTAMP,
    started_at         TIMESTAMP,
    finished_at        TIMESTAMP,
    original_sql       TEXT
)
DISTRIBUTED BY (job_id);

CREATE INDEX IF NOT EXISTS idx_job_history_job_id ON public.job_history (job_id);
CREATE INDEX IF NOT EXISTS idx_job_history_recorded_at ON public.job_history (recorded_at);


-- ─────────────────────────────────────────────────────────────────────────
-- 3) task_history — 각 executor 의 task 단위 실행 이력 (history.db_dsn)
--    DISTRIBUTED BY (job_id): 한 task_id 의 행들은 모두 같은 job_id 에 속하므로
--    job 으로 분산해도 DISTINCT ON (task_id) dedup 이 세그먼트 로컬에서 끝나고,
--    한 job 의 모든 task 가 같은 세그먼트에 co-locate 된다.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.task_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recorded_at  TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Seoul'),
    job_id       TEXT NOT NULL,
    task_id      TEXT NOT NULL,
    username     TEXT,
    executor_id  TEXT,
    status       TEXT NOT NULL,
    rows_written BIGINT,
    error        TEXT,
    started_at   TIMESTAMP,   -- task 가 READING 을 시작한 시각
    finished_at  TIMESTAMP,   -- task 가 종료(DONE/FAILED/CANCELLED)된 시각
    sub_query    TEXT,          -- 이 task 가 실행한 SELECT sub-query 전문
    exec_mode    TEXT,          -- 적재 방식: copy | statement | stage_insert
    staging_ddl  TEXT,          -- stage_insert 의 staging(TEMP) 생성 DDL
    insert_sql   TEXT,          -- stage_insert 의 INSERT 문(staging→target)
    rows_read     BIGINT,       -- Impala 에서 읽어들인 행수(=조회 건수, STREAM_COPY 종료 시 확정)
    read_wait_ms  BIGINT,       -- STREAM_COPY 중 Impala 읽기(fetch) 누적 시간(ms)
    write_wait_ms BIGINT,       -- STREAM_COPY 중 Greenplum 쓰기(write_row 인코딩+송신) 누적 시간(ms)
    read_starve_ms BIGINT,      -- (파이프라인) 라이터가 다음 배치를 기다린 시간(ms). 크면 Impala 병목
    finalize_wait_ms BIGINT,    -- COPY 종료(PQputCopyEnd)+서버 ingest 완료 대기(ms). 크면 서버 병목
    impala_done_at TIMESTAMP,   -- Impala 조회 완료 시각(STREAM_COPY 종료)
    phases        JSONB         -- 세부 단계 타임라인(각 단계 시작/종료/소요/행수/지표)
)
DISTRIBUTED BY (job_id);

-- 구버전 테이블 보강(앱도 자동 수행). 이미 있으면 무시된다.
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS started_at  TIMESTAMP;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS finished_at TIMESTAMP;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS sub_query   TEXT;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS exec_mode   TEXT;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS staging_ddl TEXT;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS insert_sql  TEXT;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS rows_read        BIGINT;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS read_wait_ms     BIGINT;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS write_wait_ms    BIGINT;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS read_starve_ms   BIGINT;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS finalize_wait_ms BIGINT;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS impala_done_at   TIMESTAMP;
ALTER TABLE public.task_history ADD COLUMN IF NOT EXISTS phases           JSONB;

CREATE INDEX IF NOT EXISTS idx_task_history_job_id ON public.task_history (job_id);
CREATE INDEX IF NOT EXISTS idx_task_history_task_id ON public.task_history (task_id);
CREATE INDEX IF NOT EXISTS idx_task_history_recorded_at ON public.task_history (recorded_at);


-- ─────────────────────────────────────────────────────────────────────────
-- 4) executor_status — executor self-report 상태 (executor.self_report=true)
--    PK(executor_id)=분산키. 각 executor 가 자기 메트릭을 주기적으로 UPSERT 하고
--    coordinator 가 읽어 /executors·/cluster 를 구성한다.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.executor_status (
    executor_id     TEXT PRIMARY KEY,
    executor_url    TEXT,          -- executor.advertise_url (HA에서 coordinator가 URL 키로 부하 뷰 구성)
    cpu_percent     DOUBLE PRECISION,
    memory_percent  DOUBLE PRECISION,
    memory_used_mb  DOUBLE PRECISION,
    memory_total_mb DOUBLE PRECISION,
    disk_percent         DOUBLE PRECISION,
    disk_used_gb         DOUBLE PRECISION,
    disk_total_gb        DOUBLE PRECISION,
    active_tasks         INTEGER,
    max_concurrent_tasks INTEGER,
    updated_at           TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Seoul')
)
DISTRIBUTED BY (executor_id);
-- 구버전 보강(executor_url 추가). 이미 있으면 무시된다.
ALTER TABLE public.executor_status ADD COLUMN IF NOT EXISTS executor_url TEXT;


-- ─────────────────────────────────────────────────────────────────────────
-- 4b) executor_reservation — (Phase 3) 공유 예약. coordinator 가 dispatch 중인 task 를
--     executor 별로 예약해 여러 coordinator 가 전역 부하를 공유한다.
--     PK(executor_url, coordinator_id) 의 부분집합인 executor_url 을 분산키로 둔다
--     (같은 executor 의 예약 행들을 한 세그먼트에 모음).
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.executor_reservation (
    executor_url   TEXT NOT NULL,
    coordinator_id TEXT NOT NULL,
    n              INTEGER NOT NULL DEFAULT 0,
    updated_at     TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Seoul'),
    PRIMARY KEY (executor_url, coordinator_id)
)
DISTRIBUTED BY (executor_url);
CREATE INDEX IF NOT EXISTS idx_executor_reservation_updated_at
    ON public.executor_reservation (updated_at);


-- ─────────────────────────────────────────────────────────────────────────
-- 4c) coordinator_status — (Phase 3) coordinator heartbeat.
--     PK(coordinator_id)=분산키. 각 coordinator 가 자기 생존을 주기적으로 UPSERT.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.coordinator_status (
    coordinator_id TEXT PRIMARY KEY,
    updated_at     TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Seoul')
)
DISTRIBUTED BY (coordinator_id);


-- ─────────────────────────────────────────────────────────────────────────
-- 5) executor_health_metrics — coordinator 가 기록하는 헬스/메트릭 (monitor.db_dsn)
--    job_id 가 없고 executor_url/시간으로 조회·집계하므로 executor_url 로 분산한다.
--    id 는 PK 가 아니라 정렬/디버그용 IDENTITY 컬럼.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.executor_health_metrics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recorded_at     TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Seoul'),
    executor_url    TEXT NOT NULL,
    healthy         BOOLEAN NOT NULL,
    cpu_percent     DOUBLE PRECISION,
    memory_percent  DOUBLE PRECISION,
    memory_used_mb  DOUBLE PRECISION,
    memory_total_mb DOUBLE PRECISION,
    disk_percent    DOUBLE PRECISION,
    error           TEXT
)
DISTRIBUTED BY (executor_url);

CREATE INDEX IF NOT EXISTS idx_executor_health_metrics_recorded_at
    ON public.executor_health_metrics (recorded_at);
CREATE INDEX IF NOT EXISTS idx_executor_health_metrics_url
    ON public.executor_health_metrics (executor_url);
